module.exports = {
    CONNECTED : 'connected',
    DISCONNECT : 'disconnect',
    CHAT_MSG : 'chat-message',
    UPDATE_CLIENTNUM : 'update-clientNum',
    CHECK_NICKNAME : 'check-nickname',
    CHECK_USERNAME : 'check-username',
    CHECK_ACCOUNT : 'check-account',
    CHECK_IP : 'check-ip',
    CREATE_ACCOUNT : 'create-account',
    SET_NICKNAME : 'set-nickname',
    CHECK_BAN_LIST : 'check-ban-list',
    GET_ALERT : 'get-alert',
    GET_NEWS : 'get-news',
};